name: Validacao de Codigo Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Python na Máquina Virtual
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar o teste da calculadora
        run: python calculadora.py
