name: Validacao de Codigo Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Python na Máquina Virtual
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar o teste da Calculadora
        run: python Calculadora.py
      - name: Executar o teste da Calculadora
        run: python Calculadora.py

      - name: Criar relatório de sucesso
        if: success() 
        run: echo "O teste da calculadora passou com sucesso no dia $(date)" > relatorio.txt

      - name: Upload do Relatório
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: meu-relatorio-de-teste
          path: relatorio.txt
